// Date: 12.06.2014 22:45:22
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.ilexiconn.jurassicraft.data.entity.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

import com.ilexiconn.jurassicraft.data.entity.EntityParasaurolophus;

public class ModelParasaurolophus extends MowzieModelBase
{
    public boolean isAlarmed;

  //fields
    MowzieModelRenderer Left_Lower_Foot;
    MowzieModelRenderer Left_Upper_Foot;
    MowzieModelRenderer Right_Lower_Foot;
    MowzieModelRenderer Right_Upper_Foot;
    MowzieModelRenderer Left_Calf_1;
    MowzieModelRenderer Right_Calf_1;
    MowzieModelRenderer Left_Thigh;
    MowzieModelRenderer Right_Thigh;
    MowzieModelRenderer Body_1;
    MowzieModelRenderer Body_2;
    MowzieModelRenderer Neck;
    MowzieModelRenderer Tail_1;
    MowzieModelRenderer Tail_2;
    MowzieModelRenderer Tail_3;
    MowzieModelRenderer Tail_4;
    MowzieModelRenderer Tail_5;
    MowzieModelRenderer Upper_Arm_Right;
    MowzieModelRenderer Upper_Arm_Left;
    MowzieModelRenderer Lower_Arm_Left;
    MowzieModelRenderer Lower_Arm_Right;
    MowzieModelRenderer Left_Hand;
    MowzieModelRenderer Right_Hand;
    MowzieModelRenderer Tail_6;
    MowzieModelRenderer Head;
    MowzieModelRenderer Snout_1;
    MowzieModelRenderer Snout_2;
    MowzieModelRenderer Jaw;
    MowzieModelRenderer Crest_1;
    MowzieModelRenderer Crest_2;
    MowzieModelRenderer Crest_3;
    MowzieModelRenderer Body_3;
    MowzieModelRenderer Foot_Left;
    MowzieModelRenderer Foot_Right;
  
  public ModelParasaurolophus()
  {
    textureWidth = 256;
    textureHeight = 256;
    
    Left_Lower_Foot = new MowzieModelRenderer(this, 98, 0);
    Left_Lower_Foot.addBox(-2F, 0F, 0F, 4, 3, 2);
    Left_Lower_Foot.setRotationPoint(7F, 20.8F, 7.7F);
    Left_Lower_Foot.setTextureSize(256, 256);
    Left_Lower_Foot.mirror = true;
    setRotation(Left_Lower_Foot, -0.9075712F, 0F, 0F);
    Left_Upper_Foot = new MowzieModelRenderer(this, 81, 0);
    Left_Upper_Foot.addBox(-2F, 0F, 0F, 3, 4, 2);
    Left_Upper_Foot.setRotationPoint(7.5F, 18F, 8.3F);
    Left_Upper_Foot.setTextureSize(256, 256);
    Left_Upper_Foot.mirror = true;
    setRotation(Left_Upper_Foot, -0.3490659F, 0F, 0F);
    Right_Lower_Foot = new MowzieModelRenderer(this, 98, 0);
    Right_Lower_Foot.addBox(-2F, 0F, 0F, 4, 3, 2);
    Right_Lower_Foot.setRotationPoint(-7.1F, 20.8F, 7.7F);
    Right_Lower_Foot.setTextureSize(256, 256);
    Right_Lower_Foot.mirror = true;
    setRotation(Right_Lower_Foot, -0.9075712F, 0F, 0F);
    Right_Upper_Foot = new MowzieModelRenderer(this, 81, 0);
    Right_Upper_Foot.addBox(-1.5F, 0F, 0F, 3, 4, 2);
    Right_Upper_Foot.setRotationPoint(-7.1F, 18F, 8.3F);
    Right_Upper_Foot.setTextureSize(256, 256);
    Right_Upper_Foot.mirror = true;
    setRotation(Right_Upper_Foot, -0.3490659F, 0F, 0F);
    Left_Calf_1 = new MowzieModelRenderer(this, 65, 0);
    Left_Calf_1.addBox(-1.5F, 0F, 0F, 3, 12, 4);
    Left_Calf_1.setRotationPoint(7F, 11.5F, 1F);
    Left_Calf_1.setTextureSize(256, 256);
    Left_Calf_1.mirror = true;
    setRotation(Left_Calf_1, 0.6283185F, 0F, 0F);
    Right_Calf_1 = new MowzieModelRenderer(this, 65, 0);
    Right_Calf_1.addBox(-1.5F, 0F, 0F, 3, 12, 4);
    Right_Calf_1.setRotationPoint(-7F, 11.5F, 1F);
    Right_Calf_1.setTextureSize(256, 256);
    Right_Calf_1.mirror = true;
    setRotation(Right_Calf_1, 0.6283185F, 0F, 0.0174533F);
    Left_Thigh = new MowzieModelRenderer(this, 27, 57);
    Left_Thigh.addBox(0F, 0F, -12F, 5, 6, 12);
    Left_Thigh.setRotationPoint(4.5F, 1F, 7F);
    Left_Thigh.setTextureSize(256, 256);
    Left_Thigh.mirror = true;
    setRotation(Left_Thigh, 0.8028515F, 0F, 0F);
    Right_Thigh = new MowzieModelRenderer(this, 27, 57);
    Right_Thigh.addBox(-5F, 0F, -12F, 5, 6, 12);
    Right_Thigh.setRotationPoint(-4.5F, 1F, 7F);
    Right_Thigh.setTextureSize(256, 256);
    Right_Thigh.mirror = true;
    setRotation(Right_Thigh, 0.8028515F, 0F, 0F);
    Body_1 = new MowzieModelRenderer(this, 122, 4);
    Body_1.addBox(-4.5F, 0F, -4F, 9, 12, 18);
    Body_1.setRotationPoint(0F, 0F, -7F);
    Body_1.setTextureSize(256, 256);
    Body_1.mirror = true;
    setRotation(Body_1, 0.0569039F, 0F, 0F);
    Body_2 = new MowzieModelRenderer(this, 182, 0);
    Body_2.addBox(-4F, 0F, 0F, 8, 9, 8);
    Body_2.setRotationPoint(0F, 4.5F, -16F);
    Body_2.setTextureSize(256, 256);
    Body_2.mirror = true;
    setRotation(Body_2, 0.5576792F, 0F, 0F);
    Neck = new MowzieModelRenderer(this, 217, 0);
    Neck.addBox(-2.5F, 0F, 0F, 5, 5, 11);
    Neck.setRotationPoint(0F, 3F, -20F);
    Neck.setTextureSize(256, 256);
    Neck.mirror = true;
    setRotation(Neck, -0.3346075F, 0F, 0F);
    Tail_1 = new MowzieModelRenderer(this, 119, 39);
    Tail_1.addBox(-4.5F, 0F, -1F, 9, 10, 10);
    Tail_1.setRotationPoint(0F, -0.4F, 10F);
    Tail_1.setTextureSize(256, 256);
    Tail_1.mirror = true;
    setRotation(Tail_1, -0.0371786F, 0F, 0F);
    Tail_2 = new MowzieModelRenderer(this, 118, 61);
    Tail_2.addBox(-4F, 0F, 0F, 8, 7, 9);
    Tail_2.setRotationPoint(0F, 1F, 16F);
    Tail_2.setTextureSize(256, 256);
    Tail_2.mirror = true;
    setRotation(Tail_2, -0.0743572F, 0F, 0F);
    Tail_3 = new MowzieModelRenderer(this, 150, 80);
    Tail_3.addBox(-3F, 0F, 0F, 6, 6, 9);
    Tail_3.setRotationPoint(0F, 2F, 22F);
    Tail_3.setTextureSize(256, 256);
    Tail_3.mirror = true;
    setRotation(Tail_3, -0.0743572F, 0F, 0F);
    Tail_4 = new MowzieModelRenderer(this, 118, 80);
    Tail_4.addBox(-2F, 0F, 0F, 4, 5, 10);
    Tail_4.setRotationPoint(0F, 3F, 29F);
    Tail_4.setTextureSize(256, 256);
    Tail_4.mirror = true;
    setRotation(Tail_4, -0.1487144F, 0F, 0F);
    Tail_5 = new MowzieModelRenderer(this, 118, 149);
    Tail_5.addBox(-1.5F, 0F, 0F, 3, 4, 10);
    Tail_5.setRotationPoint(0F, 4.3F, 35F);
    Tail_5.setTextureSize(256, 256);
    Tail_5.mirror = true;
    setRotation(Tail_5, -0.185895F, 0F, 0F);
    Upper_Arm_Right = new MowzieModelRenderer(this, 0, 56);
    Upper_Arm_Right.addBox(-3F, 0F, 0F, 3, 3, 7);
    Upper_Arm_Right.setRotationPoint(-4.5F, 8F, -7F);
    Upper_Arm_Right.setTextureSize(256, 256);
    Upper_Arm_Right.mirror = true;
    setRotation(Upper_Arm_Right, -1.07818F, 0F, 0F);
    Upper_Arm_Left = new MowzieModelRenderer(this, 0, 56);
    Upper_Arm_Left.addBox(0F, 0F, 0F, 3, 3, 7);
    Upper_Arm_Left.setRotationPoint(4.5F, 8F, -7F);
    Upper_Arm_Left.setTextureSize(256, 256);
    Upper_Arm_Left.mirror = true;
    setRotation(Upper_Arm_Left, -1.07818F, 0F, 0F);
    Lower_Arm_Left = new MowzieModelRenderer(this, 0, 70);
    Lower_Arm_Left.addBox(-1F, 0F, 0F, 2, 5, 1);
    Lower_Arm_Left.setRotationPoint(6F, 13F, -6F);
    Lower_Arm_Left.setTextureSize(256, 256);
    Lower_Arm_Left.mirror = true;
    setRotation(Lower_Arm_Left, -0.6320364F, 0F, 0F);
    Lower_Arm_Right = new MowzieModelRenderer(this, 0, 70);
    Lower_Arm_Right.addBox(-1F, 0F, 0F, 2, 5, 1);
    Lower_Arm_Right.setRotationPoint(-6F, 13F, -6F);
    Lower_Arm_Right.setTextureSize(256, 256);
    Lower_Arm_Right.mirror = true;
    setRotation(Lower_Arm_Right, -0.6320364F, 0F, 0F);
    Left_Hand = new MowzieModelRenderer(this, 0, 83);
    Left_Hand.addBox(-1F, 0F, 0F, 2, 3, 1);
    Left_Hand.setRotationPoint(6F, 17F, -9F);
    Left_Hand.setTextureSize(256, 256);
    Left_Hand.mirror = true;
    setRotation(Left_Hand, -0.0371786F, 0F, 0F);
    Right_Hand = new MowzieModelRenderer(this, 0, 83);
    Right_Hand.addBox(-1F, 0F, 0F, 2, 3, 1);
    Right_Hand.setRotationPoint(-6F, 17F, -9F);
    Right_Hand.setTextureSize(256, 256);
    Right_Hand.mirror = true;
    setRotation(Right_Hand, -0.0371786F, 0F, 0F);
    Tail_6 = new MowzieModelRenderer(this, 118, 100);
    Tail_6.addBox(-1F, 0F, 0F, 2, 3, 8);
    Tail_6.setRotationPoint(0F, 6.2F, 43F);
    Tail_6.setTextureSize(256, 256);
    Tail_6.mirror = true;
    setRotation(Tail_6, -0.2974289F, 0F, 0F);
    Head = new MowzieModelRenderer(this, 217, 40);
    Head.addBox(-3F, 0F, 0F, 6, 6, 6);
    Head.setRotationPoint(0F, 2F, -24F);
    Head.setTextureSize(256, 256);
    Head.mirror = true;
    setRotation(Head, 0F, 0F, 0F);
    Snout_1 = new MowzieModelRenderer(this, 217, 23);
    Snout_1.addBox(-2.5F, 0F, -6F, 5, 2, 6);
    Snout_1.setRotationPoint(0F, 4F, -23.1F);
    Snout_1.setTextureSize(256, 256);
    Snout_1.mirror = true;
    setRotation(Snout_1, 0F, 0F, 0F);
    Snout_2 = new MowzieModelRenderer(this, 217, 58);
    Snout_2.addBox(-2F, 0F, 0F, 4, 2, 6);
    Snout_2.setRotationPoint(0F, 4F, -29F);
    Snout_2.setTextureSize(256, 256);
    Snout_2.mirror = true;
    setRotation(Snout_2, 0.2974289F, 0F, 0F);
    Jaw = new MowzieModelRenderer(this, 217, 71);
    Jaw.addBox(-1.5F, 0F, 0F, 3, 1, 6);
    Jaw.setRotationPoint(0F, 7F, -22F);
    Jaw.setTextureSize(256, 256);
    Jaw.mirror = true;
    setRotation(Jaw, -3.141593F, 0F, 0F);
    Crest_1 = new MowzieModelRenderer(this, 0, 32);
    Crest_1.addBox(-1F, 0F, 0F, 2, 6, 2);
    Crest_1.setRotationPoint(0F, 5.5F, -27F);
    Crest_1.setTextureSize(256, 256);
    Crest_1.mirror = true;
    setRotation(Crest_1, 2.156352F, 0F, 0F);
    Crest_2 = new MowzieModelRenderer(this, 0, 32);
    Crest_2.addBox(-1F, 0F, 0F, 2, 6, 2);
    Crest_2.setRotationPoint(0F, 2.6F, -22.5F);
    Crest_2.setTextureSize(256, 256);
    Crest_2.mirror = true;
    setRotation(Crest_2, 1.970459F, 0F, 0F);
    Crest_3 = new MowzieModelRenderer(this, 0, 32);
    Crest_3.addBox(-1F, 0F, 0F, 2, 5, 2);
    Crest_3.setRotationPoint(0F, 0.6F, -17.6F);
    Crest_3.setTextureSize(256, 256);
    Crest_3.mirror = true;
    setRotation(Crest_3, 1.710209F, 0F, 0F);
    Body_3 = new MowzieModelRenderer(this, 118, 118);
    Body_3.addBox(-5.5F, 0F, 0F, 11, 13, 13);
    Body_3.setRotationPoint(0F, -1F, 0F);
    Body_3.setTextureSize(256, 256);
    Body_3.mirror = true;
    setRotation(Body_3, -0.0349066F, 0F, 0F);
    Foot_Left = new MowzieModelRenderer(this, 0, 20);
    Foot_Left.addBox(-2F, -2F, 0F, 4, 2, 6);
    Foot_Left.setRotationPoint(7F, 22F, 8F);
    Foot_Left.setTextureSize(256, 256);
    Foot_Left.mirror = true;
    setRotation(Foot_Left, 3.141593F, 0F, 0F);
    Foot_Right = new MowzieModelRenderer(this, 0, 20);
    Foot_Right.addBox(-2F, -2F, 0F, 4, 2, 6);
    Foot_Right.setRotationPoint(-7.1F, 22F, 8F);
    Foot_Right.setTextureSize(256, 256);
    Foot_Right.mirror = true;
    setRotation(Foot_Right, 3.141593F, 0F, 0F);
        
      addChildTo(Snout_1, Head);
      addChildTo(Snout_2, Head);
      addChildTo(Jaw, Head);
      addChildTo(Crest_1, Head);
      addChildTo(Crest_2, Head);
      addChildTo(Crest_3, Head);
      
      addChildTo(Foot_Right, Right_Lower_Foot);
      addChildTo(Right_Lower_Foot, Right_Upper_Foot);
      addChildTo(Right_Upper_Foot, Right_Calf_1);
      addChildTo(Right_Calf_1, Right_Thigh);
      
      addChildTo(Foot_Left, Left_Lower_Foot);
      addChildTo(Left_Lower_Foot, Left_Upper_Foot);
      addChildTo(Left_Upper_Foot, Left_Calf_1);
      addChildTo(Left_Calf_1, Left_Thigh);
      
      //Corrections
      Crest_3.setRotationPoint(0, Crest_3.rotationPointY, 6);
      Crest_3.offsetY -= 0.17F;
      
      Left_Lower_Foot.setInitValuesToCurrentPose();
      Left_Upper_Foot.setInitValuesToCurrentPose();
      Right_Lower_Foot.setInitValuesToCurrentPose();
      Right_Upper_Foot.setInitValuesToCurrentPose();
      Left_Calf_1.setInitValuesToCurrentPose();
      Right_Calf_1.setInitValuesToCurrentPose();
      Left_Thigh.setInitValuesToCurrentPose();
      Right_Thigh.setInitValuesToCurrentPose();
      Body_1.setInitValuesToCurrentPose();
      Body_2.setInitValuesToCurrentPose();
      Neck.setInitValuesToCurrentPose();
      Tail_1.setInitValuesToCurrentPose();
      Tail_2.setInitValuesToCurrentPose();
      Tail_3.setInitValuesToCurrentPose();
      Tail_4.setInitValuesToCurrentPose();
      Tail_5.setInitValuesToCurrentPose();
      Upper_Arm_Right.setInitValuesToCurrentPose();
      Upper_Arm_Left.setInitValuesToCurrentPose();
      Lower_Arm_Left.setInitValuesToCurrentPose();
      Lower_Arm_Right.setInitValuesToCurrentPose();
      Left_Hand.setInitValuesToCurrentPose();
      Right_Hand.setInitValuesToCurrentPose();
      Tail_6.setInitValuesToCurrentPose();
      Head.setInitValuesToCurrentPose();
      Snout_1.setInitValuesToCurrentPose();
      Snout_2.setInitValuesToCurrentPose();
      Jaw.setInitValuesToCurrentPose();
      Crest_1.setInitValuesToCurrentPose();
      Crest_2.setInitValuesToCurrentPose();
      Crest_3.setInitValuesToCurrentPose();
      Body_3.setInitValuesToCurrentPose();
      Foot_Left.setInitValuesToCurrentPose();
      Foot_Right.setInitValuesToCurrentPose();
  }
  
  public boolean setAlarmed(boolean setAlarm)
  {
  	return this.isAlarmed = setAlarm;
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
//    Left_Lower_Foot.render(f5);
//    Left_Upper_Foot.render(f5);
//    Right_Lower_Foot.render(f5);
//    Right_Upper_Foot.render(f5);
//    Left_Calf_1.render(f5);
//    Right_Calf_1.render(f5);
    Left_Thigh.render(f5);
    Right_Thigh.render(f5);
    Body_1.render(f5);
    Body_2.render(f5);
    Neck.render(f5);
    Tail_1.render(f5);
    Tail_2.render(f5);
    Tail_3.render(f5);
    Tail_4.render(f5);
    Tail_5.render(f5);
    Upper_Arm_Right.render(f5);
    Upper_Arm_Left.render(f5);
    Lower_Arm_Left.render(f5);
    Lower_Arm_Right.render(f5);
    Left_Hand.render(f5);
    Right_Hand.render(f5);
    Tail_6.render(f5);
    Head.render(f5);
//    Snout_1.render(f5);
//    Snout_2.render(f5);
//    Jaw.render(f5);
//    Crest_1.render(f5);
//    Crest_2.render(f5);
//    Crest_3.render(f5);
    Body_3.render(f5);
    Foot_Left.render(f5);
    Foot_Right.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
//    faceTarget(Head, 1, f3, f4);
    walk(Right_Thigh, 0.5F, 0.5F, false, 0F, f, f1);
    walk(Left_Thigh, 0.5F, 0.5F, true, 0F, f, f1);
  }

}
