// Date: 14.06.2014 17:17:05
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.ilexiconn.jurassicraft.data.entity.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelBrachiosaur extends ModelBase
{
  //fields
    ModelRenderer hips;
    ModelRenderer body_1;
    ModelRenderer body_2;
    ModelRenderer body_3;
    ModelRenderer top_leg_left;
    ModelRenderer bottom_leg_left;
    ModelRenderer left_back_foot;
    ModelRenderer front_left_top_leg;
    ModelRenderer bottom_front_left_leg;
    ModelRenderer front_left_foot;
    ModelRenderer tail1;
    ModelRenderer tail2;
    ModelRenderer tail3;
    ModelRenderer tail4;
    ModelRenderer tail5;
    ModelRenderer neck1;
    ModelRenderer neck2;
    ModelRenderer neck3;
    ModelRenderer neck4;
    ModelRenderer neck5;
    ModelRenderer neck6;
    ModelRenderer neck7;
    ModelRenderer head;
    ModelRenderer snout;
    ModelRenderer jaw;
    ModelRenderer front_right_top_leg;
    ModelRenderer bottom_front_right_leg;
    ModelRenderer front_right_foot;
    ModelRenderer top_leg_right;
    ModelRenderer bottom_leg_right;
    ModelRenderer right_back_foot;
    ModelRenderer nose;
  
  public ModelBrachiosaur()
  {
    textureWidth = 512;
    textureHeight = 256;
    
      hips = new ModelRenderer(this, 0, 155);
      hips.addBox(-9F, -9F, -11F, 18, 17, 19);
      hips.setRotationPoint(0F, -7F, 0F);
      hips.setTextureSize(512, 256);
      hips.mirror = true;
      setRotation(hips, -0.1152878F, 0F, 0F);
      body_1 = new ModelRenderer(this, 0, 109);
      body_1.addBox(-10F, -1F, -16F, 20, 20, 20);
      body_1.setRotationPoint(0F, -17F, -6F);
      body_1.setTextureSize(512, 256);
      body_1.mirror = true;
      setRotation(body_1, -0.2312985F, 0F, 0F);
      body_2 = new ModelRenderer(this, 0, 53);
      body_2.addBox(-11F, 0F, 0F, 22, 23, 20);
      body_2.setRotationPoint(0F, -28F, -30F);
      body_2.setTextureSize(512, 256);
      body_2.mirror = true;
      setRotation(body_2, -0.3432994F, 0F, 0F);
      body_3 = new ModelRenderer(this, 300, 53);
      body_3.addBox(-8F, 0F, -3F, 16, 20, 15);
      body_3.setRotationPoint(0F, -21.4F, -20F);
      body_3.setTextureSize(512, 256);
      body_3.mirror = true;
      setRotation(body_3, -1.421479F, 0F, 0F);
      top_leg_left = new ModelRenderer(this, 124, 0);
      top_leg_left.addBox(0F, 0F, -4F, 7, 21, 11);
      top_leg_left.setRotationPoint(9F, -12F, 1F);
      top_leg_left.setTextureSize(512, 256);
      top_leg_left.mirror = true;
      setRotation(top_leg_left, -0.4363323F, 0F, 0F);
      bottom_leg_left = new ModelRenderer(this, 173, 0);
      bottom_leg_left.addBox(-3F, 0F, 0F, 6, 18, 7);
      bottom_leg_left.setRotationPoint(12.5F, 4.7F, -11F);
      bottom_leg_left.setTextureSize(512, 256);
      bottom_leg_left.mirror = true;
      setRotation(bottom_leg_left, 0.5061455F, 0F, 0F);
      left_back_foot = new ModelRenderer(this, 217, 0);
      left_back_foot.addBox(-3F, 0F, -3F, 6, 7, 7);
      left_back_foot.setRotationPoint(12.5F, 17F, -0.2F);
      left_back_foot.setTextureSize(512, 256);
      left_back_foot.mirror = true;
      setRotation(left_back_foot, 0F, 0F, 0F);
      front_left_top_leg = new ModelRenderer(this, 173, 39);
      front_left_top_leg.addBox(0F, -2F, -5F, 6, 16, 9);
      front_left_top_leg.setRotationPoint(10F, -8F, -27F);
      front_left_top_leg.setTextureSize(512, 256);
      front_left_top_leg.mirror = true;
      setRotation(front_left_top_leg, 0.3839724F, 0F, 0F);
      bottom_front_left_leg = new ModelRenderer(this, 173, 78);
      bottom_front_left_leg.addBox(-3F, -6F, -1F, 6, 18, 7);
      bottom_front_left_leg.setRotationPoint(13F, 5.5F, -27F);
      bottom_front_left_leg.setTextureSize(512, 256);
      bottom_front_left_leg.mirror = true;
      setRotation(bottom_front_left_leg, -0.4283017F, 0F, 0F);
      front_left_foot = new ModelRenderer(this, 172, 117);
      front_left_foot.addBox(-3F, 0F, -3F, 6, 8, 7);
      front_left_foot.setRotationPoint(13F, 16F, -30F);
      front_left_foot.setTextureSize(512, 256);
      front_left_foot.mirror = true;
      setRotation(front_left_foot, 0F, 0F, 0F);
      tail1 = new ModelRenderer(this, 0, 205);
      tail1.addBox(-8F, -5F, 0F, 16, 14, 12);
      tail1.setRotationPoint(0F, -10.5F, 5F);
      tail1.setTextureSize(512, 256);
      tail1.mirror = true;
      setRotation(tail1, -0.4322299F, 0F, 0F);
      tail2 = new ModelRenderer(this, 78, 189);
      tail2.addBox(-6F, -5F, 0F, 12, 11, 13);
      tail2.setRotationPoint(0F, -5.8F, 12F);
      tail2.setTextureSize(512, 256);
      tail2.mirror = true;
      setRotation(tail2, -0.50385F, 0F, 0F);
      tail3 = new ModelRenderer(this, 165, 215);
      tail3.addBox(-4F, -7F, 0F, 8, 8, 17);
      tail3.setRotationPoint(0F, 0.5F, 15F);
      tail3.setTextureSize(512, 256);
      tail3.mirror = true;
      setRotation(tail3, -0.4240186F, 0F, 0F);
      tail4 = new ModelRenderer(this, 99, 223);
      tail4.addBox(-2F, 0F, 0F, 4, 6, 21);
      tail4.setRotationPoint(0F, -2F, 22F);
      tail4.setTextureSize(512, 256);
      tail4.mirror = true;
      setRotation(tail4, -0.3469243F, 0F, 0F);
      tail5 = new ModelRenderer(this, 229, 222);
      tail5.addBox(-1.5F, 0F, 0F, 3, 4, 17);
      tail5.setRotationPoint(0F, 4.3F, 34F);
      tail5.setTextureSize(512, 256);
      tail5.mirror = true;
      setRotation(tail5, -0.2353885F, 0F, 0F);
      neck1 = new ModelRenderer(this, 400, 120);
      neck1.addBox(-6F, -3F, -15F, 12, 11, 15);
      neck1.setRotationPoint(0F, -18.7F, -27F);
      neck1.setTextureSize(512, 256);
      neck1.mirror = true;
      setRotation(neck1, -0.8425631F, 0F, 0F);
      neck2 = new ModelRenderer(this, 400, 86);
      neck2.addBox(-4.5F, -5F, -21F, 9, 8, 18);
      neck2.setRotationPoint(0F, -23.2F, -37.5F);
      neck2.setTextureSize(512, 256);
      neck2.mirror = true;
      setRotation(neck2, -1.097366F, 0F, 0F);
      neck3 = new ModelRenderer(this, 400, 58);
      neck3.addBox(-3.5F, -3F, -21F, 7, 6, 12);
      neck3.setRotationPoint(0F, -30.1F, -42F);
      neck3.setTextureSize(512, 256);
      neck3.mirror = true;
      setRotation(neck3, -1.237303F, 0F, 0F);
      neck4 = new ModelRenderer(this, 400, 39);
      neck4.addBox(-3.5F, -3F, -5F, 7, 6, 5);
      neck4.setRotationPoint(0F, -49F, -48.5F);
      neck4.setTextureSize(512, 256);
      neck4.mirror = true;
      setRotation(neck4, -0.9378305F, 0F, 0F);
      neck5 = new ModelRenderer(this, 431, 0);
      neck5.addBox(-3.5F, -5F, -3F, 7, 6, 3);
      neck5.setRotationPoint(0F, -51F, -52.3F);
      neck5.setTextureSize(512, 256);
      neck5.mirror = true;
      setRotation(neck5, -0.7147588F, 0F, 0F);
      neck6 = new ModelRenderer(this, 431, 0);
      neck6.addBox(-3.5F, -6F, 0F, 7, 6, 3);
      neck6.setRotationPoint(0F, -52.8F, -56.7F);
      neck6.setTextureSize(512, 256);
      neck6.mirror = true;
      setRotation(neck6, -0.4916871F, 0F, 0F);
      neck7 = new ModelRenderer(this, 431, 0);
      neck7.addBox(-3.5F, -6F, 0F, 7, 6, 3);
      neck7.setRotationPoint(0F, -52.6F, -57.8F);
      neck7.setTextureSize(512, 256);
      neck7.mirror = true;
      setRotation(neck7, -0.1570796F, 0F, 0F);
      head = new ModelRenderer(this, 99, 71);
      head.addBox(-4F, 0F, -8F, 8, 7, 8);
      head.setRotationPoint(0F, -59F, -56F);
      head.setTextureSize(512, 256);
      head.mirror = true;
      setRotation(head, 0F, 0F, 0F);
      snout = new ModelRenderer(this, 45, 13);
      snout.addBox(-2.5F, -2F, -7F, 5, 4, 7);
      snout.setRotationPoint(0F, -55.5F, -63F);
      snout.setTextureSize(512, 256);
      snout.mirror = true;
      setRotation(snout, 0F, 0F, 0F);
      jaw = new ModelRenderer(this, 0, 23);
      jaw.addBox(-2F, 0F, -6F, 4, 1, 6);
      jaw.setRotationPoint(0F, -53.5F, -63.5F);
      jaw.setTextureSize(512, 256);
      jaw.mirror = true;
      setRotation(jaw, 0F, 0F, 0F);
      front_right_top_leg = new ModelRenderer(this, 173, 39);
      front_right_top_leg.addBox(-6F, -2F, -5F, 6, 16, 9);
      front_right_top_leg.setRotationPoint(-10F, -8F, -27F);
      front_right_top_leg.setTextureSize(512, 256);
      front_right_top_leg.mirror = true;
      setRotation(front_right_top_leg, 0.3839724F, 0F, 0F);
      bottom_front_right_leg = new ModelRenderer(this, 173, 78);
      bottom_front_right_leg.addBox(-3F, -6F, -1F, 6, 18, 7);
      bottom_front_right_leg.setRotationPoint(-13F, 5.5F, -27F);
      bottom_front_right_leg.setTextureSize(512, 256);
      bottom_front_right_leg.mirror = true;
      setRotation(bottom_front_right_leg, -0.4283017F, 0F, 0F);
      front_right_foot = new ModelRenderer(this, 172, 117);
      front_right_foot.addBox(-3F, 0F, -3F, 6, 8, 7);
      front_right_foot.setRotationPoint(-13F, 16F, -30F);
      front_right_foot.setTextureSize(512, 256);
      front_right_foot.mirror = true;
      setRotation(front_right_foot, 0F, 0F, 0F);
      top_leg_right = new ModelRenderer(this, 124, 0);
      top_leg_right.addBox(-7F, 0F, -4F, 7, 21, 11);
      top_leg_right.setRotationPoint(-9F, -12F, 1F);
      top_leg_right.setTextureSize(512, 256);
      top_leg_right.mirror = true;
      setRotation(top_leg_right, -0.4363323F, 0F, 0F);
      bottom_leg_right = new ModelRenderer(this, 173, 0);
      bottom_leg_right.addBox(-3F, 0F, 0F, 6, 18, 7);
      bottom_leg_right.setRotationPoint(-12.5F, 4.7F, -11F);
      bottom_leg_right.setTextureSize(512, 256);
      bottom_leg_right.mirror = true;
      setRotation(bottom_leg_right, 0.5061455F, 0F, 0F);
      right_back_foot = new ModelRenderer(this, 217, 0);
      right_back_foot.addBox(-3F, 0F, -3F, 6, 7, 7);
      right_back_foot.setRotationPoint(-12.5F, 17F, -0.2F);
      right_back_foot.setTextureSize(512, 256);
      right_back_foot.mirror = true;
      setRotation(right_back_foot, 0F, 0F, 0F);
      nose = new ModelRenderer(this, 35, 30);
      nose.addBox(-1.5F, -8F, -4F, 3, 8, 8);
      nose.setRotationPoint(0F, -54.5F, -62F);
      nose.setTextureSize(512, 256);
      nose.mirror = true;
      setRotation(nose, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    hips.render(f5);
    body_1.render(f5);
    body_2.render(f5);
    body_3.render(f5);
    top_leg_left.render(f5);
    bottom_leg_left.render(f5);
    left_back_foot.render(f5);
    front_left_top_leg.render(f5);
    bottom_front_left_leg.render(f5);
    front_left_foot.render(f5);
    tail1.render(f5);
    tail2.render(f5);
    tail3.render(f5);
    tail4.render(f5);
    tail5.render(f5);
    neck1.render(f5);
    neck2.render(f5);
    neck3.render(f5);
    neck4.render(f5);
    neck5.render(f5);
    neck6.render(f5);
    neck7.render(f5);
    head.render(f5);
    snout.render(f5);
    jaw.render(f5);
    front_right_top_leg.render(f5);
    bottom_front_right_leg.render(f5);
    front_right_foot.render(f5);
    top_leg_right.render(f5);
    bottom_leg_right.render(f5);
    right_back_foot.render(f5);
    nose.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
  }

}
